#pragma once

#include <vector>
#include <map>
#include <string>
#include <queue>
#include <memory>

#include "event.h"
#include "data_handler.h"

class Strategy {
    /*
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars 
    (OLHCVI) generated by a DataHandler object.

    This is designed to work both with historic and live data as
    the Strategy object is agnostic to the data source,
    since it obtains the bar vecotrs from a queue object.
    */
public:
    virtual ~Strategy() = default;
    virtual void calculateSignals() = 0;
};